# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\JenIKs\PycharmProjects\install_first\front.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect, QSize, QTime, QUrl, Qt, QEvent)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PySide2.QtWidgets import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1087, 663)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setStyleSheet("background-color: rgb(26, 40, 58);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top_Bar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.Top_Bar)
        self.frame_toggle.setMaximumSize(QtCore.QSize(70, 40))
        self.frame_toggle.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Btn_Toggle = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Toggle.sizePolicy().hasHeightForWidth())
        self.Btn_Toggle.setSizePolicy(sizePolicy)
        self.Btn_Toggle.setStyleSheet("QPushButton {\n"
"   color: rgb(255, 255, 255);;\n"
"   background-color: rgb(37, 53, 75);;\n"
"   border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: rgb(48, 70, 98);\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color:rgb(79, 115, 161);\n"
"}")
        self.Btn_Toggle.setObjectName("Btn_Toggle")
        self.verticalLayout_2.addWidget(self.Btn_Toggle)
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_top = QtWidgets.QFrame(self.Top_Bar)
        self.frame_top.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_top.setStyleSheet("background-color: rgb(37, 53, 75);")
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.pushButton = QtWidgets.QPushButton(self.frame_top)
        self.pushButton.setGeometry(QtCore.QRect(980, 0, 41, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"   color: rgb(255, 255, 255);;\n"
"   background-color: rgb(37, 53, 75);\n"
"   border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: rgb(79, 115, 161);\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color:rgb(48, 70, 98);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_top)
        self.pushButton_3.setGeometry(QtCore.QRect(940, 0, 41, 41))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"   color: rgb(255, 255, 255);;\n"
"   background-color: rgb(37, 53, 75);\n"
"   border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: rgb(79, 115, 161);\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color:rgb(48, 70, 98);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.raise_()
        self.pushButton.raise_()
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(37, 53, 75);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_page_1 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_1.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_1.setStyleSheet("QPushButton {\n"
"   color: rgb(255, 255, 255);;\n"
"   background-color: rgb(37, 53, 75);;\n"
"   border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: rgb(48, 70, 98);\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color:rgb(79, 115, 161);\n"
"}")
        self.btn_page_1.setObjectName("btn_page_1")
        self.verticalLayout_4.addWidget(self.btn_page_1)
        self.btn_page_2 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_2.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_2.setStyleSheet("QPushButton {\n"
"   color: rgb(255, 255, 255);;\n"
"   background-color: rgb(37, 53, 75);;\n"
"   border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: rgb(48, 70, 98);\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color:rgb(79, 115, 161);\n"
"}")
        self.btn_page_2.setObjectName("btn_page_2")
        self.verticalLayout_4.addWidget(self.btn_page_2)
        self.btn_page_3 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_3.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_3.setStyleSheet("QPushButton {\n"
"   color: rgb(255, 255, 255);;\n"
"   background-color: rgb(37, 53, 75);;\n"
"   border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: rgb(48, 70, 98);\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color:rgb(79, 115, 161);\n"
"}")
        self.btn_page_3.setObjectName("btn_page_3")
        self.verticalLayout_4.addWidget(self.btn_page_3)
        self.verticalLayout_3.addWidget(self.frame_top_menus, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page_1)
        self.scrollArea_2.setStyleSheet("QScrollArea {\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar:vertical {\n"
"border: none;\n"
"background: #1a283a;\n"
"width: 14px;\n"
"margin: 15px 0 15px 0;\n"
"border-radius: 0px;\n"
"}\n"
"QScrollBar:vertical {\n"
"background: #25354b;\n"
"width: 15px;\n"
"margin: 0;\n"
"border: 15 px;\n"
"}\n"
"\n"
"/* HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {\n"
"background-color: #1a283a;\n"
"min-height: 30px;\n"
"border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{\n"
"background-color: rgb(79, 115, 161);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {\n"
"background-color: rgb(48, 70, 98);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical {\n"
"background: #7c8ea5;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"height: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"height: 0px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"border: none;\n"
"background: #1a283a;\n"
"width: 14px;\n"
"margin: 15px 0 15px 0;\n"
"border-radius: 0px;\n"
"}\n"
"QScrollBar:horizontal {\n"
"background: #25354b;\n"
"width: 15px;\n"
"margin: 0;\n"
"border: 15 px;\n"
"}\n"
"\n"
"/* HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:horizontal {\n"
"background-color: #1a283a;\n"
"min-height: 30px;\n"
"border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{\n"
"background-color: rgb(79, 115, 161);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {\n"
"background-color: rgb(48, 70, 98);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"background: none;\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"background: #7c8ea5;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"height: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"height: 0px;\n"
"}")
        self.scrollArea_2.setWidgetResizable(False)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 946, 703))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame.setStyleSheet("background-color: #7c8ea5;\n"
"border-radius: 10px;border-radius")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_2.setStyleSheet("background-color: #7c8ea5;\n"
"border-radius: 10px;border-radius")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2.addWidget(self.frame_2, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_3.setStyleSheet("background-color: #7c8ea5;\n"
"border-radius: 10px;border-radius")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2.addWidget(self.frame_3, 0, 2, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_4.setStyleSheet("background-color: #7c8ea5;\n"
"border-radius: 10px;border-radius")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2.addWidget(self.frame_4, 1, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_5.setStyleSheet("background-color: #7c8ea5;\n"
"border-radius: 10px;border-radius")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_2.addWidget(self.frame_5, 1, 1, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_6.setStyleSheet("background-color: #7c8ea5;\n"
"border-radius: 10px;border-radius")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_2.addWidget(self.frame_6, 1, 2, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_7.setStyleSheet("background-color: #7c8ea5;\n"
"border-radius: 10px;border-radius")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_2.addWidget(self.frame_7, 2, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_7.addWidget(self.scrollArea_2)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea = QtWidgets.QScrollArea(self.page_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1044, 937))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #FFF;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.label)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_Toggle.setText(_translate("MainWindow", "->"))
        self.pushButton.setText(_translate("MainWindow", "X"))
        self.pushButton_3.setText(_translate("MainWindow", "_"))
        self.btn_page_1.setText(_translate("MainWindow", "Браузеры"))
        self.btn_page_2.setText(_translate("MainWindow", "Утилиты"))
        self.btn_page_3.setText(_translate("MainWindow", "Лаунчеры"))
        self.label.setText(_translate("MainWindow", "PAGE 3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
